name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Increment Version
        run: ./gradlew incrementVersion -Pmode=minor

      - name: Retrieve Version
        run: |
          echo "version_name=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment version ${{ env.version_name }}
          tagging_message:  ${{ env.version_name }}
      - name: Retrieve all context
        run: echo "$GITHUB_CONTEXT"
      - name: Use the value
        run: |
          echo "${{ env.version_name }}" # This will output 'yellow'
      - name: Checkout new commit  ${{ github.head_ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/dyeimys/events-api:latest,ghcr.io/dyeimys/events-api:${{ env.version_name }}