name: Docker Image CI

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  commit-new-version:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Increment Version
        run: ./gradlew incrementVersion -Pmode=minor

      - name: Retrieve Version
        run: |
          echo "version_name=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          message: Commit new version - ${{ env.version_name }}
          push: false
          tag: ${{ env.version_name }}

      - name: Pushing to the protected branch 'main'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          ref: main
          tags: True
