name: Docker pull Image

on:
  push:
    tags:
      - '**'
jobs:
  generate-image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Retrieve Version
        run: |
          echo "version_name=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/dyeimys/events-api:latest,ghcr.io/dyeimys/events-api:${{ env.version_name }}